"""Induced-profile writer (profile induction architecture, Phase 2 /
Task 4).

This module is the final stage of the discovery / induction
pipeline. It consumes a list of *scored* :class:`CandidateConcept`
instances (output of :func:`ontozense.core.relevance.score_candidates`)
and emits a draft profile directory plus an
:class:`~ontozense.core.discovery_contracts.InductionReport`.

The emitted directory follows the existing
:mod:`ontozense.core.profile` layout exactly, so the same loader
the profile-mode pipeline already uses can read the induced output
without any loader change. That is *the* acceptance criterion for
this task — call it AC1 in the implementation plan.

## What lands where

The architecture's "Entity type induction" section says: cluster
candidates under a limited set of induced top-level types, prefer
``Concept`` for business-like candidates and ``TechnicalArtifact``
for technical-like ones. This module honours that by:

  - emitting ``Concept`` as a top-level entity type, with the
    ``core_business``-classified candidates' labels as its
    subtypes;
  - emitting ``TechnicalArtifact`` (only if any
    ``supporting_technical`` candidates exist) with that band's
    labels as subtypes;
  - excluding ``noise`` candidates from the schema and surfacing
    them in the report's ``rejected_examples`` so a reviewer can
    see why they were dropped.

Predicate, alias, and required-field induction (also in the
architecture's design) are deliberately out of scope for v1: the
plan scopes them as follow-up tasks, and predicate induction in
particular needs the ``CandidateRelationship`` list which this
function's signature does not accept.

## Sidecar files

In addition to ``schema.json``, the function emits the three
sidecar files the profile loader supports:

  - ``alias_map.json`` — initially empty ``{}``. Alias induction is
    a follow-up task; we still write the file so the directory has
    a fixed shape for downstream tooling.
  - ``prompt_fragment.md`` — domain-neutral guidance for the
    constrained second pass, loaded into ``Profile.prompt_fragment``.
  - ``induction_report.json`` — the audit trail, including the
    exact ``scoring_weights`` and ``scoring_thresholds`` the
    induction used so a reviewer can reproduce the bands.

## Conflict handling

The profile loader rejects certain malformed schemas:

  - subtype names that collide with a top-level entity-type name;
  - the same subtype name appearing under two different parents.

Candidates whose labels would trigger either condition are dropped
from the schema and surfaced in the report's ``review_notes`` so
the schema stays loader-valid even on messy input. The candidate
itself still appears in the report's ``top_candidates`` or
``rejected_examples`` — only the schema subtype is suppressed.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .discovery_contracts import CandidateConcept, InductionReport
from .relevance import DEFAULT_THRESHOLDS, DEFAULT_WEIGHTS


# ─── Module constants ──────────────────────────────────────────────────────

# The two top-level entity types the architecture's
# "Entity type induction" section §1-2 prescribes.
_BUSINESS_TYPE = "Concept"
_TECHNICAL_TYPE = "TechnicalArtifact"
_RESERVED_TYPE_NAMES = {_BUSINESS_TYPE.lower(), _TECHNICAL_TYPE.lower()}

# Cap report list sizes so the JSON stays human-reviewable even on
# large extractions. Top / rejected lists are sorted by score, so
# the cap surfaces the most relevant items.
_TOP_CANDIDATE_LIMIT = 25
_REJECTED_EXAMPLE_LIMIT = 25

_PROMPT_FRAGMENT_BODY = """# Induced profile — draft

This profile was generated by ``ontozense induce-profile`` from a
candidate graph. Treat it as a starting draft, not a final source
of truth.

Conservative extraction guidance:

  - Emit entities whose labels match one of the listed subtypes
    under ``Concept`` or ``TechnicalArtifact``, or whose meaning
    clearly aligns with that type's required / optional fields.
  - Treat clean business-named labels as ``Concept``. Treat
    labels with technical-implementation patterns (e.g. ``tmp_*``
    prefix, ``_id`` suffix, internal-key shapes) as
    ``TechnicalArtifact``.
  - Review and amend ``schema.json``, ``alias_map.json``, and this
    fragment before running the constrained rebuild — the induced
    version intentionally errs on the side of being conservative.
"""


# ─── Public API ────────────────────────────────────────────────────────────


def write_induced_profile(
    domain_name: str,
    candidates: list[CandidateConcept],
    out_dir: str | Path,
    *,
    weights: dict[str, float] | None = None,
    thresholds: dict[str, float] | None = None,
) -> Path:
    """Write an induced profile directory + induction report.

    Parameters
    ----------
    domain_name : str
        Becomes ``profile_name`` in the emitted ``schema.json``.
    candidates : list[CandidateConcept]
        Scored candidates (``classification`` populated). Typically
        the output of :func:`score_candidates`.
    out_dir : str | Path
        Target directory. Created if it doesn't exist.
    weights : dict[str, float] | None
        The weights used during scoring. Recorded in
        ``induction_report.scoring_weights`` so the run is
        reproducible. Defaults to :data:`DEFAULT_WEIGHTS` when
        ``None`` — matches the scoring-stage default.
    thresholds : dict[str, float] | None
        The classification thresholds used during scoring. Recorded
        in ``induction_report.scoring_thresholds`` for the same
        reason. Defaults to :data:`DEFAULT_THRESHOLDS`.

    Returns
    -------
    Path
        ``out_dir`` as a :class:`Path`. The four emitted files are:

          - ``schema.json``
          - ``alias_map.json``
          - ``prompt_fragment.md``
          - ``induction_report.json``
    """
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    # Defensive copy — the report stores these maps verbatim and we
    # don't want a later mutation of the caller's dict to leak in.
    weight_map = dict(DEFAULT_WEIGHTS if weights is None else weights)
    threshold_map = dict(
        DEFAULT_THRESHOLDS if thresholds is None else thresholds
    )

    # Bucket by classification. Everything not selected lands in
    # ``rejected`` so the report's counts reconcile exactly:
    #
    #   candidate_count
    #     == selected_core_count + selected_supporting_count
    #        + rejected_count
    #
    # That includes the documented "noise" band *and* any candidate
    # whose classification is something else (e.g. the dataclass
    # default ``"unknown"`` when ``score_candidates`` was skipped,
    # or a hypothetical future band a caller invented). Without
    # this catch-all, candidates with non-standard classifications
    # would silently disappear from both ``top_candidates`` and
    # ``rejected_examples`` and the report would no longer be a
    # full audit trail.
    core = [c for c in candidates if c.classification == "core_business"]
    supporting = [
        c for c in candidates
        if c.classification == "supporting_technical"
    ]
    rejected = [
        c for c in candidates
        if c.classification not in (
            "core_business", "supporting_technical",
        )
    ]

    review_notes: list[str] = []

    # Surface non-"noise" rejected classifications so a reviewer
    # notices upstream-pipeline drift (typically a forgotten
    # ``score_candidates`` step). The aggregate per-classification
    # form keeps the note compact even on large inputs; the
    # individual candidates still appear in ``rejected_examples``.
    non_standard = sorted({
        c.classification for c in rejected
        if c.classification != "noise"
    })
    if non_standard:
        review_notes.append(
            f"{len(rejected) - sum(1 for c in rejected if c.classification == 'noise')} "
            f"candidate(s) carried non-standard classification(s) "
            f"{non_standard!r}; counted as rejected. Run "
            f"score_candidates() before write_induced_profile() to "
            f"assign one of the documented bands."
        )

    schema, emitted_types = _build_schema(
        domain_name, core, supporting, review_notes,
    )
    (out_path / "schema.json").write_text(
        json.dumps(schema, indent=2) + "\n", encoding="utf-8",
    )
    (out_path / "alias_map.json").write_text(
        json.dumps({}, indent=2) + "\n", encoding="utf-8",
    )
    (out_path / "prompt_fragment.md").write_text(
        _PROMPT_FRAGMENT_BODY, encoding="utf-8",
    )

    selected_sorted = sorted(
        core + supporting,
        key=lambda c: c.relevance_score,
        reverse=True,
    )
    rejected_sorted = sorted(
        rejected, key=lambda c: c.relevance_score, reverse=True,
    )

    if not core and not supporting:
        review_notes.append(
            "No candidates were classified as core_business or "
            "supporting_technical. The schema declares the type "
            "buckets but they are empty — broaden the inputs or "
            "relax the scoring thresholds before running rebuild."
        )

    report = InductionReport(
        domain_name=domain_name,
        generated_at=datetime.now(timezone.utc).isoformat(),
        candidate_count=len(candidates),
        selected_core_count=len(core),
        selected_supporting_count=len(supporting),
        rejected_count=len(rejected),
        scoring_weights=weight_map,
        top_candidates=[
            _top_candidate_entry(c)
            for c in selected_sorted[:_TOP_CANDIDATE_LIMIT]
        ],
        rejected_examples=[
            _rejected_entry(c)
            for c in rejected_sorted[:_REJECTED_EXAMPLE_LIMIT]
        ],
        predicate_suggestions=[],
        required_field_suggestions={
            t: ["definition"] for t in emitted_types
        },
        review_notes=review_notes,
        scoring_thresholds=threshold_map,
    )
    (out_path / "induction_report.json").write_text(
        json.dumps(report.to_dict(), indent=2) + "\n",
        encoding="utf-8",
    )
    return out_path


# ─── Schema construction ──────────────────────────────────────────────────


def _build_schema(
    domain_name: str,
    core: list[CandidateConcept],
    supporting: list[CandidateConcept],
    review_notes: list[str],
) -> tuple[dict[str, Any], list[str]]:
    """Build the loader-compatible schema dict.

    Returns ``(schema_dict, emitted_type_names)``. The caller uses
    the emitted-type list to size ``required_field_suggestions`` so
    the report only mentions types that actually appear in the
    schema.
    """
    emitted_types: list[str] = [_BUSINESS_TYPE]

    core_subtypes = _subtypes_from_candidates(
        core,
        parent_type=_BUSINESS_TYPE,
        already_used_lower=set(),
        review_notes=review_notes,
    )

    entity_types: dict[str, Any] = {
        _BUSINESS_TYPE: {
            "required": ["definition"],
            "optional": ["source_reference"],
            "subtypes": core_subtypes,
        }
    }

    if supporting:
        # Pass the set of lower-cased subtypes already claimed by
        # Concept so a label that lands in both bands doesn't trip
        # the loader's cross-parent collision check.
        already_lower = {s.lower() for s in core_subtypes}
        supporting_subtypes = _subtypes_from_candidates(
            supporting,
            parent_type=_TECHNICAL_TYPE,
            already_used_lower=already_lower,
            review_notes=review_notes,
        )
        entity_types[_TECHNICAL_TYPE] = {
            "required": ["definition"],
            "optional": ["source_reference"],
            "subtypes": supporting_subtypes,
        }
        emitted_types.append(_TECHNICAL_TYPE)

    schema: dict[str, Any] = {
        "profile_name": domain_name,
        "profile_version": "0.1.0",
        "description": f"Induced draft profile for {domain_name}",
        "entity_types": entity_types,
        # Predicate / alias / canonical-verb induction are
        # follow-up tasks. The keys are present (so the schema is
        # symmetric with hand-authored profiles) but empty.
        "predicates": {},
        "alias_map": {},
        "canonical_verbs": {},
        "id_format": {
            "strategy": "type_label_hash",
            "pattern": "{entity_type_lower}_{normalized_label}_{hash6}",
            "hash_length": 6,
        },
    }
    return schema, emitted_types


def _subtypes_from_candidates(
    candidates: list[CandidateConcept],
    *,
    parent_type: str,
    already_used_lower: set[str],
    review_notes: list[str],
) -> list[str]:
    """Extract a deduplicated, loader-safe subtype list from a
    classification bucket.

    Drops three kinds of problematic labels (and logs each in
    ``review_notes`` when dropped):

      - empty / whitespace-only;
      - labels that match a reserved top-level type name (would
        crash the loader's "subtype shadows top-level" check);
      - labels already claimed by another parent's subtypes (would
        crash the loader's cross-parent collision check).

    Within a single bucket, duplicates (case-insensitive) are kept
    once. The returned list is sorted for deterministic schema
    output — important for diff-friendly review.
    """
    seen_lower: set[str] = set()
    out: list[str] = []
    for candidate in candidates:
        label = candidate.label.strip()
        if not label:
            review_notes.append(
                f"Candidate {candidate.candidate_id!r} has an empty / "
                f"whitespace-only label; excluded from {parent_type} "
                f"subtypes. Check the source ingestion stage for a "
                f"missing or stripped name."
            )
            continue
        lower = label.lower()
        if lower in _RESERVED_TYPE_NAMES:
            review_notes.append(
                f"Candidate {candidate.candidate_id!r} has label "
                f"{label!r}, which collides with a reserved top-level "
                f"type name; excluded from {parent_type} subtypes."
            )
            continue
        if lower in already_used_lower:
            review_notes.append(
                f"Candidate {candidate.candidate_id!r} has label "
                f"{label!r}, which is already a subtype under another "
                f"top-level type; excluded from {parent_type} "
                f"subtypes to keep the schema loader-valid."
            )
            continue
        if lower in seen_lower:
            continue
        seen_lower.add(lower)
        out.append(label)
    return sorted(out)


# ─── Report entry helpers ─────────────────────────────────────────────────


def _top_candidate_entry(candidate: CandidateConcept) -> dict[str, Any]:
    """Compact projection of a selected candidate for the report's
    ``top_candidates`` array."""
    return {
        "candidate_id": candidate.candidate_id,
        "label": candidate.label,
        "classification": candidate.classification,
        "score": candidate.relevance_score,
    }


def _rejected_entry(candidate: CandidateConcept) -> dict[str, Any]:
    """Same projection for ``rejected_examples`` — kept separate so
    later phases can diverge the two shapes without churn here."""
    return {
        "candidate_id": candidate.candidate_id,
        "label": candidate.label,
        "score": candidate.relevance_score,
    }
