"""Source D ingester — extracts candidates from Python source files.

Pure AST-based; no LLM calls. The existing
``code_extractor.py`` provides a more elaborate pattern (deterministic
parse + LLM labelling), but its LLM step is marked future work in
its own docstring. This v1.1 ingester uses only the deterministic
AST output, classifying via Python-native shapes (class, dataclass,
Enum, etc.).

Task 10 scaffold: classes / dataclasses / Pydantic BaseModel /
SQLAlchemy-style models emit as ENTITY at STRONG strength. Private
classes (``_*``) are suppressed by default. Tasks 11-13 add fields,
Enum, methods, rules, DTO flag, and full noise filters.

See the design spec §3.3, §7 for the determinism property and the
artifact taxonomy.
"""

from __future__ import annotations

import ast
import logging
from pathlib import Path
from typing import Any, Iterable

from .base import (
    ArtifactKind,
    IngestionPolicy,
    IntermediateCandidate,
    Strength,
)
from .filters import (
    DEFAULT_SOURCE_D_CLASS_SUPPRESSIONS,
    glob_match,
    path_match,
)

logger = logging.getLogger(__name__)


# Class-base names that mark a class as a Pydantic/SQLAlchemy/dataclass-style model.
ENTITY_BASE_NAMES: set[str] = {
    "BaseModel",          # Pydantic
    "Base",               # SQLAlchemy declarative_base()
    "Document",           # Mongo / Beanie
}

DTO_SUFFIXES: tuple[str, ...] = (
    "DTO", "Request", "Response", "Schema", "Model",
)

GENERATED_MARKERS: tuple[str, ...] = (
    "# DO NOT EDIT",
    "# Generated by",
    "# AUTOGENERATED",
    "# This file was automatically generated",
)


class SourceDIngester(IngestionPolicy):
    """Ingester for Source D — Python AST."""

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        self.config = config or {}

    def ingest(self, raw_input: Any) -> Iterable[IntermediateCandidate]:
        if not isinstance(raw_input, dict):
            return

        user_exclude_paths = self.config.get("exclude_paths", []) or []
        user_exclude_classes = self.config.get("exclude_classes", []) or []
        user_include_classes = self.config.get("include_classes", []) or []
        user_force_vocabulary = self.config.get("force_vocabulary", []) or []

        from .filters import DEFAULT_SOURCE_D_PATH_SUPPRESSIONS

        for path_str in raw_input.get("files", []) or []:
            path = Path(path_str)
            if path.suffix.lower() != ".py":
                continue

            # ─── Path-based suppression ────────────────────────────────
            # Normalise the path for glob matching: forward slashes only,
            # case-insensitive (the glob_match helper already
            # lower-cases the patterns).
            path_str_norm = str(path).replace("\\", "/")

            path_suppressed = False
            path_suppression_reason: str | None = None

            for p in user_exclude_paths:
                if path_match(path_str_norm, [p]):
                    path_suppressed = True
                    path_suppression_reason = (
                        f"Per-domain config: path matches "
                        f"exclude_paths pattern '{p}'."
                    )
                    break

            if not path_suppressed:
                for p in DEFAULT_SOURCE_D_PATH_SUPPRESSIONS:
                    if path_match(path_str_norm, [p]):
                        path_suppressed = True
                        path_suppression_reason = (
                            f"Default Source D suppression: path matches "
                            f"pattern '{p}'."
                        )
                        break

            # ─── Read file (needed for both generated-marker check and AST) ──
            try:
                raw_text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue

            # ─── Generated-code marker check (first 5 lines) ───────────
            if not path_suppressed:
                first_lines = "\n".join(raw_text.splitlines()[:5])
                for marker in GENERATED_MARKERS:
                    if marker in first_lines:
                        path_suppressed = True
                        path_suppression_reason = (
                            f"Source D: file contains generated-code "
                            f"marker '{marker}'."
                        )
                        break

            if path_suppressed:
                # Emit a single suppressed-marker candidate for the audit.
                yield IntermediateCandidate(
                    label=str(path.name),
                    definition="",
                    source_type="D",
                    source_artifact=str(path),
                    raw_type="suppressed_file",
                    eid="",
                    artifact_kind=ArtifactKind.ENTITY,
                    strength=Strength.WEAK,
                    promotion_reason="",
                    suppression_reason=path_suppression_reason,
                    suppressed=True,
                )
                continue

            # ─── Parse and walk the AST ────────────────────────────────
            try:
                tree = ast.parse(raw_text)
            except SyntaxError as exc:
                logger.warning(
                    "Source D: could not parse %s (%s); skipping.",
                    path, exc,
                )
                continue
            yield from self._yield_for_module(
                tree, path,
                user_exclude_classes=user_exclude_classes,
                user_include_classes=user_include_classes,
                user_force_vocabulary=user_force_vocabulary,
            )

    def _yield_for_module(
        self,
        tree: ast.Module,
        source_path: Path,
        *,
        user_exclude_classes: list[str] | None = None,
        user_include_classes: list[str] | None = None,
        user_force_vocabulary: list[str] | None = None,
    ) -> Iterable[IntermediateCandidate]:
        user_exclude_classes = user_exclude_classes or []
        user_include_classes = user_include_classes or []
        user_force_vocabulary = user_force_vocabulary or []

        for node in tree.body:
            if not isinstance(node, ast.ClassDef):
                continue
            if glob_match(node.name, DEFAULT_SOURCE_D_CLASS_SUPPRESSIONS):
                continue

            # ─── Class-level suppression via user config ──────────────
            # Check BEFORE classification so that even unrecognised shapes
            # (e.g. a factory with only methods) get a suppressed marker.
            class_suppressed = False
            class_suppression_reason: str | None = None
            if glob_match(node.name, user_exclude_classes):
                class_suppressed = True
                for p in user_exclude_classes:
                    if glob_match(node.name, [p]):
                        class_suppression_reason = (
                            f"Per-domain config: class '{node.name}' matches "
                            f"exclude_classes pattern '{p}'."
                        )
                        break

            raw_type = self._classify_class_node(node)
            # If class is suppressed by user config, emit the suppressed marker
            # even when the classifier returns None (unrecognised shape).
            if raw_type is None:
                if class_suppressed:
                    yield IntermediateCandidate(
                        label=node.name,
                        definition=ast.get_docstring(node) or "",
                        source_type="D",
                        source_artifact=f"{source_path}:{node.lineno}",
                        raw_type="class",
                        eid="",
                        artifact_kind=ArtifactKind.ENTITY,
                        strength=Strength.STRONG,
                        promotion_reason="",
                        suppression_reason=class_suppression_reason,
                        suppressed=True,
                    )
                continue

            class_is_force_included = glob_match(node.name, user_include_classes)

            if raw_type == "enum":
                yield IntermediateCandidate(
                    label=node.name,
                    definition=ast.get_docstring(node) or "",
                    source_type="D",
                    source_artifact=f"{source_path}:{node.lineno}",
                    raw_type="enum",
                    eid="",
                    artifact_kind=ArtifactKind.VOCABULARY,
                    strength=Strength.MEDIUM,
                    promotion_reason=(
                        f"Source D: Enum subclass '{node.name}' "
                        f"({source_path.name}:{node.lineno})."
                    ),
                    suppression_reason=class_suppression_reason,
                    suppressed=class_suppressed,
                )
                continue

            # ─── DTO flag for Pydantic models with DTO-suffix names ───
            emitted_raw_type = raw_type
            if (
                raw_type == "pydantic_model"
                and any(node.name.endswith(s) for s in DTO_SUFFIXES)
                and not class_is_force_included
            ):
                emitted_raw_type = "dto_candidate"

            # ─── force_vocabulary override ────────────────────────────
            # When the class name matches a force_vocabulary glob pattern,
            # override the artifact_kind to VOCABULARY at MEDIUM strength.
            # Enums are already VOCABULARY and are handled above; this path
            # only runs for non-enum classes. (spec §7.4)
            if user_force_vocabulary and glob_match(node.name, user_force_vocabulary):
                matched_pattern = next(
                    p for p in user_force_vocabulary if glob_match(node.name, [p])
                )
                yield IntermediateCandidate(
                    label=node.name,
                    definition=ast.get_docstring(node) or "",
                    source_type="D",
                    source_artifact=f"{source_path}:{node.lineno}",
                    raw_type=emitted_raw_type,
                    eid="",
                    artifact_kind=ArtifactKind.VOCABULARY,
                    strength=Strength.MEDIUM,
                    promotion_reason=(
                        f"Source D: {emitted_raw_type} '{node.name}' "
                        f"reclassified to vocabulary by force_vocabulary "
                        f"pattern '{matched_pattern}' "
                        f"({source_path.name}:{node.lineno})."
                    ),
                    suppression_reason=class_suppression_reason,
                    suppressed=class_suppressed,
                )
                if class_suppressed:
                    continue
                # Emit fields for the force-vocabulary class.
                for stmt in node.body:
                    if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
                        field_name = stmt.target.id
                        type_annotation = self._render_annotation(stmt.annotation)
                        yield IntermediateCandidate(
                            label=field_name,
                            definition="",
                            source_type="D",
                            source_artifact=(
                                f"{source_path}:{node.name}.{field_name}:{stmt.lineno}"
                            ),
                            raw_type=type_annotation,
                            eid="",
                            artifact_kind=ArtifactKind.ATTRIBUTE,
                            strength=Strength.STRONG,
                            promotion_reason=(
                                f"Source D: field '{node.name}.{field_name}' "
                                f"(type {type_annotation})."
                            ),
                            suppression_reason=None,
                            suppressed=False,
                        )
                continue

            # ─── Emit entity ──────────────────────────────────────────
            yield IntermediateCandidate(
                label=node.name,
                definition=ast.get_docstring(node) or "",
                source_type="D",
                source_artifact=f"{source_path}:{node.lineno}",
                raw_type=emitted_raw_type,
                eid="",
                artifact_kind=ArtifactKind.ENTITY,
                strength=Strength.STRONG,
                promotion_reason=(
                    f"Source D: {emitted_raw_type} '{node.name}' "
                    f"({source_path.name}:{node.lineno})."
                ),
                suppression_reason=class_suppression_reason,
                suppressed=class_suppressed,
            )

            # If the class is suppressed, do NOT emit its fields or methods.
            # The audit shows the class-level marker; we keep the audit lean.
            if class_suppressed:
                continue

            # ─── Class fields → ATTRIBUTE ─────────────────────────────
            for stmt in node.body:
                if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
                    field_name = stmt.target.id
                    type_annotation = self._render_annotation(stmt.annotation)
                    yield IntermediateCandidate(
                        label=field_name,
                        definition="",
                        source_type="D",
                        source_artifact=(
                            f"{source_path}:{node.name}.{field_name}:{stmt.lineno}"
                        ),
                        raw_type=type_annotation,
                        eid="",
                        artifact_kind=ArtifactKind.ATTRIBUTE,
                        strength=Strength.STRONG,
                        promotion_reason=(
                            f"Source D: field '{node.name}.{field_name}' "
                            f"(type {type_annotation})."
                        ),
                        suppression_reason=None,
                        suppressed=False,
                    )

            # ─── Class methods → BEHAVIOR ─────────────────────────────
            for stmt in node.body:
                if isinstance(stmt, ast.FunctionDef) and not stmt.name.startswith("_"):
                    yield IntermediateCandidate(
                        label=f"{node.name}.{stmt.name}",
                        definition=ast.get_docstring(stmt) or "",
                        source_type="D",
                        source_artifact=(
                            f"{source_path}:{node.name}.{stmt.name}:{stmt.lineno}"
                        ),
                        raw_type="method",
                        eid="",
                        artifact_kind=ArtifactKind.BEHAVIOR,
                        strength=Strength.WEAK,
                        promotion_reason=(
                            f"Source D: method '{node.name}.{stmt.name}' "
                            f"({source_path.name}:{stmt.lineno})."
                        ),
                        suppression_reason=None,
                        suppressed=False,
                    )

        # ─── Module-level functions: validate_*/check_*/assert_* → RULE ──
        for node in tree.body:
            if isinstance(node, ast.FunctionDef):
                if (node.name.startswith("validate_")
                        or node.name.startswith("check_")
                        or node.name.startswith("assert_")):
                    yield IntermediateCandidate(
                        label=node.name,
                        definition=ast.get_docstring(node) or "",
                        source_type="D",
                        source_artifact=f"{source_path}:{node.lineno}",
                        raw_type="validation_function",
                        eid="",
                        artifact_kind=ArtifactKind.RULE,
                        strength=Strength.WEAK,
                        promotion_reason=(
                            f"Source D: validation function "
                            f"'{node.name}' ({source_path.name}:{node.lineno})."
                        ),
                        suppression_reason=None,
                        suppressed=False,
                    )

    @staticmethod
    def _classify_class_node(node: ast.ClassDef) -> str | None:
        """Return a raw_type string for entity-flavoured classes, or
        None when the class doesn't look like a domain entity.

        Order of checks:
          1. Enum subclass (Enum / IntEnum / StrEnum / Flag / IntFlag) -> 'enum'
          2. @dataclass decorator -> 'dataclass'
          3. Pydantic BaseModel base -> 'pydantic_model'
          4. SQLAlchemy / known entity base -> 'sqlalchemy_model'
          5. Plain class with at least one annotated attribute -> 'class'
          6. Otherwise None.
        """
        # Enum detection (base must be Enum or a known Enum subclass name).
        for base in node.bases:
            base_name = (
                base.id if isinstance(base, ast.Name)
                else base.attr if isinstance(base, ast.Attribute)
                else None
            )
            if base_name in ("Enum", "IntEnum", "StrEnum", "Flag", "IntFlag"):
                return "enum"

        has_dataclass_decorator = any(
            (isinstance(d, ast.Name) and d.id == "dataclass") or
            (isinstance(d, ast.Call) and isinstance(d.func, ast.Name)
                and d.func.id == "dataclass")
            for d in node.decorator_list
        )
        if has_dataclass_decorator:
            return "dataclass"

        for base in node.bases:
            base_name = (
                base.id if isinstance(base, ast.Name)
                else base.attr if isinstance(base, ast.Attribute)
                else None
            )
            if base_name == "BaseModel":
                return "pydantic_model"
            if base_name in ENTITY_BASE_NAMES:
                return "sqlalchemy_model"

        has_annotated_attr = any(
            isinstance(stmt, ast.AnnAssign)
            for stmt in node.body
        )
        if has_annotated_attr:
            return "class"

        return None

    @staticmethod
    def _render_annotation(node: ast.expr) -> str:
        """Render a type annotation AST node back to a string."""
        try:
            return ast.unparse(node)
        except Exception:
            return ""
