"""Source D ingester — entry point for the survey command.

The detailed extraction lives in the source_d package
(``src/ontozense/core/ingest/source_d/``). This file owns the
``{"files": [...]}`` manifest contract, path-level filtering, and the
IngestionPolicy interface.

v1.1 internals (_yield_for_module, _classify_class_node, _render_annotation,
ENTITY_BASE_NAMES, DTO_SUFFIXES) have been deleted. All extraction logic
now lives in the source_d package (Task 15).
"""
from __future__ import annotations

import logging
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from .base import IngestionPolicy, IntermediateCandidate
from .filters import (
    DEFAULT_SOURCE_D_PATH_SUPPRESSIONS,
    path_match,
)
from . import source_d

logger = logging.getLogger(__name__)

# Generated-code markers (first 5 lines of file, substring match).
GENERATED_MARKERS: tuple[str, ...] = (
    "# DO NOT EDIT",
    "# Generated by",
    "# AUTOGENERATED",
    "# This file was automatically generated",
)


class SourceDIngester(IngestionPolicy):
    """Source D ingester — Python AST via the source_d package."""

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        self.config = config or {}

    def ingest(self, raw_input: Any) -> Iterable[IntermediateCandidate]:
        if not isinstance(raw_input, dict):
            return

        user_exclude_paths = list(self.config.get("exclude_paths", []) or [])

        for path_str in raw_input.get("files", []) or []:
            path = Path(path_str)
            if path.suffix.lower() != ".py":
                continue

            # ── Path-based suppression ──────────────────────────────────
            # Normalise: forward slashes only (case-insensitive via path_match).
            path_str_norm = str(path).replace("\\", "/")

            path_suppressed = False
            path_suppression_reason: str | None = None

            for p in user_exclude_paths:
                if path_match(path_str_norm, [p]):
                    path_suppressed = True
                    path_suppression_reason = (
                        f"Per-domain config: path matches "
                        f"exclude_paths pattern '{p}'."
                    )
                    break

            if not path_suppressed:
                for p in DEFAULT_SOURCE_D_PATH_SUPPRESSIONS:
                    if path_match(path_str_norm, [p]):
                        path_suppressed = True
                        path_suppression_reason = (
                            f"Default Source D suppression: path matches "
                            f"pattern '{p}'."
                        )
                        break

            # ── Read file (needed for generated-marker check) ───────────
            try:
                raw_text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue

            # ── Generated-code marker check (first 5 lines) ─────────────
            if not path_suppressed:
                first_lines = "\n".join(raw_text.splitlines()[:5])
                for marker in GENERATED_MARKERS:
                    if marker in first_lines:
                        path_suppressed = True
                        path_suppression_reason = (
                            f"Source D: file contains generated-code "
                            f"marker '{marker}'."
                        )
                        break

            if path_suppressed:
                from .base import ArtifactKind, Strength
                yield IntermediateCandidate(
                    label=str(path.name),
                    definition="",
                    source_type="D",
                    source_artifact=str(path),
                    raw_type="suppressed_file",
                    eid="",
                    artifact_kind=ArtifactKind.ENTITY,
                    strength=Strength.WEAK,
                    promotion_reason="",
                    suppression_reason=path_suppression_reason,
                    suppressed=True,
                )
                continue

            yield from source_d.run(path, config=self.config)
